### ISSUE TITLE
Allow the format be specified as a single string

### ISSUE THREAD

**Issue by bsutton** [tejainece/date_format#43]
The current formatting method is a little painful
```dart
  var _message = '${formatDate(DateTime.now(), [
        'yy',
        '-',
        'M',
        '-',
        'd',
        ' ',
        'h',
        ':',
        'm',
        ':',
        's'
      ])} $message}';
```
It would be nicer if you could do:

```dart
print(${formatDate(DateTime.now(), 'yy-M-d h:m:s')}');
```

**Comment by tejainece** [comment]
This package **deliberately** avoids date format strings like in other languages/libraries. 
This approach provides the following benefits:

1. Strongly Typed means less runtime error prone
2. String date format specifications are typo-prone
3. This faster that parsing string date format specification
4. Less code because there is no code needed to parse string date format
5. Date format parts can be code completed
